# Generated by Django 2.1.5 on 2019-01-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='movie_id',
            new_name='douban_id',
        ),
    ]
