# Generated by Django 2.1.5 on 2019-01-08 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentcontent', models.TextField()),
                ('commenttime', models.DateTimeField(default=django.utils.timezone.now)),
                ('commentexist', models.IntegerField(default=1)),
                ('commentarticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
                ('commentuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Likeit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeittime', models.DateTimeField(default=django.utils.timezone.now)),
                ('likeitexist', models.IntegerField(default=0)),
                ('likeitarticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
                ('likeituser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
